[package]
authors = ["B. Blechschmidt"]
edition = "2018"
name = "tun2proxy"
version = "0.1.1"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
base64 = { version = "0.21" }
clap = { version = "4.3", features = ["derive"] }
ctrlc = "3.4"
digest_auth = "0.3.1"
dotenvy = "0.15"
env_logger = "0.10"
fork = "0.1"
hashlink = "0.8"
httparse = "1.8.0"
libc = "0.2"
log = "0.4"
mio = { version = "0.8", features = ["os-poll", "net", "os-ext"] }
nix = { version = "0.26", features = ["process", "signal"] }
prctl = "1.0"
smoltcp = { version = "0.10.0", features = ["std", "phy-tuntap_interface"] }
thiserror = "1.0"
unicase = "2.6.0"
url = "2.4"

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.13"
jni = { version = "0.21", default-features = false }

[dev-dependencies]
ctor = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serial_test = "2.0"
test-log = "0.2"
