[package]
authors = ["B. Blechschmidt"]
edition = "2018"
name = "tun2proxy"
version = "0.1.1"

[dependencies]
base64 = { version = "0.21" }
clap = { version = "4.1", features = ["derive"] }
dotenv = "0.15"
env_logger = "0.10"
log = "0.4"
mio = { version = "0.8", features = ["os-poll", "net", "os-ext"] }
smoltcp = { version = "0.9", features = ["std"] }
url = "2.3"

[dev-dependencies]
ctor = "0.1"
fork = "0.1"
nix = { version = "0.26", features = ["process", "signal"] }
prctl = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serial_test = "1.0"
