[export]
include = [
    "tun2proxy_with_fd_run",
    "tun2proxy_with_name_run",
    "tun2proxy_with_name_stop",
    "tun2proxy_with_fd_stop",
    "tun2proxy_set_log_callback",
]
exclude = [
    "Java_com_github_shadowsocks_bg_Tun2proxy_run",
    "Java_com_github_shadowsocks_bg_Tun2proxy_stop",
]
